# Generated by Django 4.1.2 on 2022-10-24 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('cost', models.CharField(max_length=100)),
                ('stuffs', models.ManyToManyField(to='main_app.stuff')),
            ],
        ),
        migrations.CreateModel(
            name='Traveling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='traveling date')),
                ('mood', models.CharField(choices=[('B', 'Bad'), ('O', 'OK'), ('G', 'Good'), ('L', 'Loved it')], default='B', max_length=1)),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vaca')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vaca')),
            ],
        ),
    ]
